### ISSUE TITLE
BUG: Every Answer Correct

### ISSUE THREAD

**Issue by fgrtgtrgtrgrt** [Minesraft2/Blooket-Cheats#535] opened 2023-03-05 18:04 UTC
### Script

everyAnswerCorrect.js

### Problem

Everytime I use this in game my game freezes on the screen where I pick my items, for example on gold quest i pick swap but it freezes after I swap and it doesn't work and I have to refresh and rejoin

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by fgrtgtrgtrgrt** [comment] 2023-03-05 18:41
I don't know why but if you could let me know if it was fixed within the update to the gui and scripts

**Comment by Minesraft2** [comment] 2023-03-05 18:41
I'll close this issue when I confirm it's fixed

**Comment by fgrtgtrgtrgrt** [comment] 2023-03-05 18:44
ok its been happening for awhile especially on gold quest

**Comment by orangemonkey01** [comment] 2023-03-06 00:16
it works for me i did it thursday

**Comment by fgrtgtrgtrgrt** [comment] 2023-03-06 11:45
it works but after a while it freezes

**Comment by Minesraft2** [comment] 2023-03-06 19:02
> it works but after a while it freezes

Send what question set you're using

**Comment by bAbAgRiL6969** [comment] 2023-03-15 18:50
Okay let me set things straight. Where. Are. The. Cheats. I dont know how these help if I cant find the hacks.

**Comment by Minesraft2** [comment] 2023-03-16 18:59
> Okay let me set things straight. Where. Are. The. Cheats. I dont know how these help if I cant find the hacks.

how blind do you have to be to still not be able to find the cheats

**Comment by Minesraft2** [comment] 2023-03-16 19:08
Also unable to reproduce

**Closed by Minesraft2** 2023-03-16 19:08 UTC
Labels: bug
